# ----------------------------------------------------------
#  CAPS-as-Hyper + Vim-style movement – AeroSpace edition
# ----------------------------------------------------------

[mode.main.binding]

# ── Basic window focus (⇪ + h/j/k/l) ───────────────────────
ctrl-shift-h = "focus left"
ctrl-shift-j = "focus down"
ctrl-shift-k = "focus up"
ctrl-shift-l = "focus right"

# ── Balance / float / fullscreen ──────────────────────────
ctrl-shift-m  = "layout floating tiling" # toggle float
ctrl-shift-f  = "fullscreen"             # toggle fullscreen

# ── Monitor focus (⇪ + ⌘ + n/p) ──────────────────────────
ctrl-shift-n = "focus-monitor next"
ctrl-shift-p = "focus-monitor prev"

# ── Send window to monitor (⇪ + ⌘ + ⇧ + n/p) ─────────────
ctrl-shift-u = "move-node-to-monitor --wrap-around next"
ctrl-shift-d = "move-node-to-monitor --wrap-around prev"

ctrl-shift-a = 'layout tiles accordion'
